import { useMemo, useState } from 'react';
import { FileText, NotebookPen, Download, Trash2, Search, Plus, ArrowLeft } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import DocumentCard from '../components/DocumentCard';
import { documents, documentBodies } from '../data/documents';
import { artifacts } from '../data/artifacts';
import useResearchNotes from '../hooks/useResearchNotes';
import useAuthGate from '../hooks/useAuthGate';
import { useAuth } from '../context/AuthContext';

export default function Research() {
  const { docId } = useParams();
  if (docId) return <DocumentReader docId={docId} />;
  return <ResearchHub />;
}

function ResearchHub() {
  const [tab, setTab] = useState('documents'); const [query, setQuery] = useState(''); const [note, setNote] = useState(''); const [artifactId, setArtifactId] = useState('');
  const { notes, addNote, removeNote } = useResearchNotes();
  const { user } = useAuth();
  const requireAuth = useAuthGate();
  const shown = useMemo(() => documents.filter(d => `${d.title} ${d.type} ${d.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())), [query]);
  const exportDoc = (doc) => { const blob = new Blob([documentBodies[doc.id] || doc.summary], {type:'text/markdown'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=`${doc.id}.md`; a.click(); URL.revokeObjectURL(url); };
  const saveNote = () => requireAuth(() => { if(!note.trim()) return; addNote({ body: note.trim(), artifactId }); setNote(''); setArtifactId(''); });
  const exportNotes = () => { const body = notes.map(n => `# Research note\n\n${n.body}\n\nArtifact: ${artifacts.find(a=>a.id===n.artifactId)?.title || 'General'}\nUpdated: ${n.updatedAt}\n`).join('\n---\n'); const blob=new Blob([body],{type:'text/markdown'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download='palimpsest-research-notes.md'; a.click(); URL.revokeObjectURL(url); };
  return <div className="mx-auto max-w-7xl px-6 lg:px-10 py-16">
    <span className="eyebrow">Research workspace</span><div className="mt-4 flex flex-col lg:flex-row lg:items-end justify-between gap-6"><div><h1 className="text-4xl sm:text-5xl">Documents, notes, and evidence.</h1><p className="mt-4 max-w-2xl text-bone-dim leading-relaxed">A lightweight research layer for the archive. Everything here persists in your browser until a backend is connected.</p></div><div className="panel px-4 py-3 font-mono text-xs text-bone-faint"><span className="text-bone">{notes.length}</span> saved notes</div></div>
    <div className="mt-10 flex gap-2 border-b border-ink-line"><button onClick={()=>setTab('documents')} className={`px-4 py-3 font-mono text-xs uppercase tracking-wider ${tab==='documents'?'text-scan border-b border-scan':'text-bone-faint'}`}><FileText className="inline w-4 h-4 mr-2"/>Documents</button><button onClick={()=>setTab('notes')} className={`px-4 py-3 font-mono text-xs uppercase tracking-wider ${tab==='notes'?'text-scan border-b border-scan':'text-bone-faint'}`}><NotebookPen className="inline w-4 h-4 mr-2"/>Research notebook</button></div>
    {tab==='documents' ? <><div className="mt-7 relative max-w-xl"><Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-bone-faint"/><input className="field pl-10" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search documents, protocols, policies..."/></div><div className="mt-7 grid md:grid-cols-2 lg:grid-cols-3 gap-6">{shown.map(d=><DocumentCard key={d.id} document={d} onExport={exportDoc}/>)}</div></> : <div className="mt-7 grid lg:grid-cols-[1fr_1.25fr] gap-6"><section className="panel p-6"><div className="flex items-center justify-between"><div><h2 className="text-2xl">New research note</h2><p className="mt-1 text-sm text-bone-dim">Keep observations attached to a record or write a general note.</p></div><Plus className="w-5 h-5 text-scan"/></div><select className="field mt-6" value={artifactId} onChange={e=>setArtifactId(e.target.value)}><option value="">General archive note</option>{artifacts.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select><textarea className="field mt-3 min-h-44 resize-y" value={note} onChange={e=>setNote(e.target.value)} placeholder={user ? "Observation, hypothesis, citation, or follow-up question..." : "Sign in to save notes to your notebook..."}/><button onClick={saveNote} className="btn-primary mt-4 w-full justify-center">{user ? <>Save note <NotebookPen className="w-4 h-4"/></> : <>Sign in to save <NotebookPen className="w-4 h-4"/></>}</button></section><section className="space-y-4"><div className="flex items-center justify-between"><h2 className="text-2xl">Saved notes</h2>{notes.length>0&&<button onClick={exportNotes} className="btn-ghost !px-3 !py-2 !text-xs"><Download className="w-3.5 h-3.5"/> Export</button>}</div>{notes.length===0?<div className="panel p-10 text-center text-bone-dim">Your research notebook is empty.</div>:notes.map(n=><article key={n.id} className="panel p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-sm text-bone whitespace-pre-wrap leading-relaxed">{n.body}</p><p className="mt-4 font-mono text-[10px] uppercase text-bone-faint">{artifacts.find(a=>a.id===n.artifactId)?.title || 'General archive note'} · {new Date(n.updatedAt).toLocaleString()}</p></div><button onClick={()=>removeNote(n.id)} className="text-bone-faint hover:text-rust-bright" aria-label="Delete note"><Trash2 className="w-4 h-4"/></button></div></article>)}</section></div>}
  </div>;
}

function DocumentReader({docId}) { const doc=documents.find(d=>d.id===docId); if(!doc) return <div className="mx-auto max-w-3xl px-6 py-24">Document not found.</div>; return <div className="mx-auto max-w-4xl px-6 lg:px-10 py-16"><Link to="/research" className="font-mono text-xs text-bone-faint hover:text-scan"><ArrowLeft className="inline w-4 h-4 mr-2"/>Back to research</Link><div className="mt-10"><span className="eyebrow">{doc.type} · v{doc.version}</span><h1 className="mt-4 text-4xl sm:text-5xl">{doc.title}</h1><p className="mt-3 text-sm text-bone-faint">Updated {doc.updated}</p></div><article className="mt-10 panel p-6 sm:p-10 prose-archive">{documentBodies[doc.id].split('\n').map((line,i)=>{if(line.startsWith('# ')) return <h2 key={i} className="text-2xl mt-2 mb-5">{line.slice(2)}</h2>; if(line.startsWith('## ')) return <h3 key={i} className="text-xl mt-8 mb-3">{line.slice(3)}</h3>; if(line.startsWith('- ')) return <li key={i} className="ml-5 text-bone-dim leading-relaxed">{line.slice(2)}</li>; if(line.startsWith('|')) return <p key={i} className="font-mono text-xs text-bone-dim overflow-x-auto whitespace-pre">{line}</p>; if(!line.trim()) return <div key={i} className="h-2"/>; return <p key={i} className="text-bone-dim leading-relaxed">{line}</p>;})}</article></div>; }
